TITLE: Kaiwa Practice
NAME: Samodra

TEXT: Topik 1: Hobi
TEXT: こんにちは、はじめまして。私は Alyssa です。Jakarta から来ました。お名前は何ですか？
VIDEO: assets/1-1.mov | CROP_TEXT: こんにちは、はじめまして。 私の名前は サモドラ です。 よろしくお願いします。
TEXT: 私の趣味は描くです。あなたはどうですか？
VIDEO: assets/1-1.mov | CROP_TEXT: 私の趣味はゲームをすることと、音楽を聞くことです

TEXT: Topik 2: Makanan Favorit
TEXT: こんにちは、はじめまして。私は Alyssa です。Jakarta から来ました。お名前は何ですか？
VIDEO: assets/2-1.mov | CROP_TEXT: 私の好きな食べ物はナシゴレンです
VIDEO: assets/2-1.mov | CROP_TEXT: 特に母のナシゴレンが大好きです
VIDEO: assets/2-1.mov | CROP_TEXT: とてもおいしいので、いつもおかわりします
