# Example Script Configuration
# Lines starting with '#' or '//' are comments and will be ignored by the builder.

TITLE: Kaiwa Practice Day 1
SUBTITLE: Samodra

# Generates a standard text slide for 3 seconds (or based on config.json)
TEXT: Topik 1: Hobi

# Generates another standard text slide
TEXT: こんにちは、はじめまして。私は Alyssa です。Jakarta から来ました。お名前は何ですか？

# Pulls in the video from assets, and uses Whisper to crop it exactly to where the speaker says the text
# Note: Format is "VIDEO: <path> | CROP_TEXT: <spoken text to find>"
VIDEO: assets/1-1.mov | CROP_TEXT: こんにちは、はじめまして。 私の名前は サモドラ です。 よろしくお願いします。

TEXT: 私の趣味は描くです。あなたはどうですか？
VIDEO: assets/1-1.mov | CROP_TEXT: 私の趣味はゲームをすることと、音楽を聞くことです。

# You can pull multiple different clips from the same source file!
VIDEO: assets/1-2.mov | CROP_TEXT: ゲームをするのが好きですが、あまりよくしません。
VIDEO: assets/1-2.mov | CROP_TEXT: でも、音楽は毎日聞きます。
